services:
    next-app:
      image: ghcr.io/roamingowl/playwright-next:latest
      container_name: next-app
      build:
        context: .
        dockerfile: next.Dockerfile
      restart: always
      ports:
        - 3000:3000

