name: Playwright running serially

on:
  workflow_dispatch:
    inputs: {}

defaults:
    run:
        shell: bash

jobs:
    playwright-serial:
        name: Playwright
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker GitHub auth
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: token
            password: ${{ secrets.WRITE_PACKAGES_TOKEN }}

        - name: Run copmose
          run: |
              docker compose up -d

        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Get npm cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

        - uses: actions/cache@v4
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: ${{ steps.npm-cache-dir.outputs.dir }}
            key: serial-playwright-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              serial-playwright-${{ runner.os }}-node-

        - run: npm i

        - run: npx playwright install --with-deps chromium

        - name: Run playwright
          env:
            NEXT_APP_URL: http://next-app:3000
          run: |
              npm playwright test 

#        - name: Publish CTRF Test Summary Results
#          run: |
#            npx github-actions-ctrf summary ctrf/ctrf-report.json
#          if: always()